name: CI/CD on PR

on:
  pull_request:

jobs:
  cd-dev:
    uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
    with:
      service-name: catalyst-stats
      docker-tag: '${{ github.sha }}'
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
